# Generated by Django 5.0.14 on 2025-10-23 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=150, verbose_name="Classes you tutor? "
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Phone number"
                    ),
                ),
                ("mon_start", models.TimeField(blank=True, null=True)),
                ("mon_end", models.TimeField(blank=True, null=True)),
                ("tue_start", models.TimeField(blank=True, null=True)),
                ("tue_end", models.TimeField(blank=True, null=True)),
                ("wed_start", models.TimeField(blank=True, null=True)),
                ("wed_end", models.TimeField(blank=True, null=True)),
                ("thu_start", models.TimeField(blank=True, null=True)),
                ("thu_end", models.TimeField(blank=True, null=True)),
                ("fri_start", models.TimeField(blank=True, null=True)),
                ("fri_end", models.TimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=10000)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
