# Generated by Django 5.0.14 on 2025-10-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="thru_end",
            new_name="thur_end",
        ),
    ]
