# Generated by Django 5.0.14 on 2025-10-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_tutorprofile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorprofile",
            name="phone",
        ),
    ]
