# Generated by Django 5.0.14 on 2025-10-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_thru_end_tutorprofile_thur_end"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="tus_end",
            new_name="tue_end",
        ),
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="tus_start",
            new_name="tue_start",
        ),
    ]
