# Generated by Django 5.2.7 on 2025-10-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_tus_end_tutorprofile_tue_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="thur_end",
            new_name="thu_end",
        ),
        migrations.RenameField(
            model_name="tutorprofile",
            old_name="thur_start",
            new_name="thu_start",
        ),
    ]
